name: bitcoin_ticker
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"




dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.2
  cupertino_icons: ^0.1.2
  flutter_spinkit: ^4.1.2+1
  

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true


  assets:
    - images/bitcoin.png
    - images/binancecoin.png
    - images/bitcoin-cash.png
    - images/chainlink.png
    - images/ethereum.png
    - images/litecoin.png
    - images/monero.png
    - images/polkadot.png
    - images/stellar.png
    - images/tether.png

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-bold.ttf
          weight: 900
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 700
    